### ISSUE TITLE
VMS with VMDK "sparse" type instead of  "thin provision", are not backed up.

### ISSUE THREAD

**Issue by itforcare** [lamw/ghettoVCB#58] opened 2015-04-09 09:51 UTC
VMS with VMDK "sparse" type instead of "thin provision", are not backed up.

Now i just exclude them but is there another solution?

**Comment by lamw** [comment] 2019-01-06 14:37
Dupe of https://github.com/lamw/ghettoVCB/issues/23

**Closed by lamw** 2019-01-06 14:37 UTC
