### ISSUE TITLE
Serious bug using exclusion files and vm's with similar names !!!

### ISSUE THREAD

**Issue by cgsit** [lamw/ghettoVCB#122] opened 2017-09-05 16:00 UTC
I am using GhettoVCB (LAST_MODIFIED_DATE=2015_05_06, VERSION=1) 
on one of my ESXi servers (ESXi 5.5 2068190 - Lenovo custom iso)
I have three VMs:
mtm-web-etec1 (first webserver)
mtm-web-etec1-old (a old copy of first webserver)
mtm-web-etec2 (secondary webserver)

If I run /path/ghettoVCB.sh -a -g /path/ghettoVCB.conf
 Ghetto saves me all three VMs (as aspected)

If I run /path/ghettoVCB.sh -a -e /path/exclusions.conf -g /path/ghettoVCB.conf
 (in exclusions.conf i wrote "mtm-web-etec1-old")
 Ghetto saves me only "mtm-web-etec2" !!!
And then send me email "ALL VMs BACKED UP OK !!!!!!

Alex

**Comment by ffejtable** [comment] 2018-08-08 12:00
This should be an easy fix.. I've only been looking at the script the last day or so to fix/enhance something else, but my guess this is a simple grep search that needs to be modified.

**Comment by ffejtable** [comment] 2018-08-08 15:10
This is likely a dupe of a previously reported issue.  See https://github.com/lamw/ghettoVCB/issues/43

As I suspected, it's a simple fix just needing a $ placed after the VM_NAME variable in the grep statement.

`grep -E "^${VM_NAME}" "${VM_EXCLUSION_FILE}" > /dev/null 2>&1`

should be

`grep -E "^${VM_NAME}$" "${VM_EXCLUSION_FILE}" > /dev/null 2>&1`

**Comment by lamw** [comment] 2019-01-06 14:15
Resolved

**Closed by lamw** 2019-01-06 14:15 UTC
